# coding: utf-8


TEMPLATE_FILE_BASE_NAME = 'bgm'
TEMPLATE_EXTENSION = '.m4a'
THUMBNAIL_FILE_NAME = 'thumbnail'
THUMBNAIL_EXTENSION = '.png'
TEMPLATE_FILE_NAME = f'{TEMPLATE_FILE_BASE_NAME}{TEMPLATE_EXTENSION}'
USER_MEDIA_DIRECTORY_NAME = 'userMedia'
