# coding: utf-8


TEMPLATE_FILE_BASE_NAME = 'bgm'
TEMPLATE_EXTENSION = '.m4a'
TEMPLATE_FILE_NAME = f'{TEMPLATE_FILE_BASE_NAME}{TEMPLATE_EXTENSION}'
THUMBNAIL_FILE_BASE_NAME = 'thumbnail'
THUMBNAIL_EXTENSION = '.png'
THUMBNAIL_FILE_NAME = f'{THUMBNAIL_FILE_BASE_NAME}{THUMBNAIL_EXTENSION}'
