runs:
  using: "composite"
  steps:
    # Ruby is already installed on the machine,
    # but for cache and bundler installation, use the following action.
    - name: Install Ruby, bundler, fastlane and other dependencies
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        bundler-cache: true
