inputs:
  google-service-json-base64-dev:
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Google service json file
      shell: bash
      run: echo "${{ inputs.google-service-json-base64-dev }}" | base64 -d > android/app/src/dev/google-services.json
