runs:
  using: "composite"
  steps:
    - name: Setup git email and name
      shell: bash
      # Set github-actions[bot] user
      # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global pull.rebase true
