inputs:
  api_test_sample_movies_zip_url:
    required: true

env:
  PYTHON_VERSION: "3.9"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      # Use the nearest version of FFMpeg installed in the environment
      # on which the production runtime is based.
      # https://cloud.google.com/functions/docs/reference/system-packages#ubuntu_1804
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg=7:3.4.11-0ubuntu0.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      working-directory: task
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download test samples
      env:
        API_TEST_SAMPLE_MOVIES_ZIP_URL: ${{ inputs.api_test_sample_movies_zip_url }}
      working-directory: task
      run: |
        mkdir samples
        cd samples
        wget -O samples.zip "${API_TEST_SAMPLE_MOVIES_ZIP_URL}"
        unzip samples.zip

    - name: Test
      working-directory: task
      run: pytest
