inputs:
  google-service-plist-base64-dev:
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Google service plist file
      shell: bash
      run: echo "${{ inputs.google-service-plist-base64-dev }}" | base64 -d > ios/Runner/Firebase/Dev/GoogleService-Info.plist
