// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3pgEgvf_2yFXV_gDiUIU1Br87Vkq50Uc',
    appId: '1:1051662796035:android:ff172b9eb418a8a3651536',
    messagingSenderId: '1051662796035',
    projectId: 'colomney-meow-music-dev',
    storageBucket: 'colomney-meow-music-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4CI0LLd7uvuk5DIrZl9pczMPh5K5n3Fg',
    appId: '1:1051662796035:ios:f165734849be5c95651536',
    messagingSenderId: '1051662796035',
    projectId: 'colomney-meow-music-dev',
    storageBucket: 'colomney-meow-music-dev.appspot.com',
    iosClientId:
        '1051662796035-hv0f57pgrrif82jf6431pjcuqgg94ho2.apps.googleusercontent.com',
    iosBundleId: 'ide.shota.colomney.MeowMusic',
  );
}
