import '../android/fastlane/Fastfile'
import '../ios/fastlane/Fastfile'

require 'yaml'

desc 'Get Flutter dependencies'
lane :install_flutter_dependencies do
  Dir.chdir('../') do
    sh('flutter pub get --no-example')
  end
end

desc 'Generate automatic codes'
lane :generate do
  Dir.chdir('../') do
    sh('flutter pub run build_runner build --delete-conflicting-outputs')
  end
end

desc 'Bump patch version'
lane :bump_patch_version do
  Dir.chdir('../') do
    sh('dart run cider bump patch --bump-build')
  end
end

desc 'Add release candidate tag'
lane :add_release_candidate_tag do
  full_version_name = get_full_version_name

  add_git_tag(
    grouping: 'rc',
    includes_lane: false,
    build_number: full_version_name
  )
end

desc 'Set full version name from latest tag'
lane :set_full_version_name_from_latest_tag do
  latest_tag_name = Dir.chdir('../') do
    sh("git describe --tags --abbrev=0 --match='rc/*'")
  end

  matched = %r{^.*/(\d+\.\d+\.\d+\+\d+)$}.match(latest_tag_name)

  full_version_name = matched[1]

  Dir.chdir('../') do
    sh("dart run cider version #{full_version_name}")
  end
end

private_lane :get_full_version_name do
  Dir.chdir('../') do
    sh('dart run cider version').chomp
  end
end

private_lane :get_version_code do
  full_version_name = get_full_version_name

  matched = /^\d+\.\d+\.\d+\+(\d+)$/.match(full_version_name)

  version_code = matched[1].to_i
  version_code
end
