default_platform(:ios)

platform :ios do
  desc 'Install iOS dependencies'
  lane :install_dependencies do
    install_flutter_dependencies

    Dir.chdir('../ios') do
      sh('flutter precache --ios')
      sh('pod install')
    end
  end

  desc 'Build develop app'
  lane :build_dev do
    generate

    build(
      flavor: 'dev',
      dart_defines_path: 'dart-defines_dev.json',
      export_options_plist_path: './ios/ExportOptions_AdHoc.plist'
    )
  end

  desc 'Build develop app with no code sign'
  lane :build_dev_with_no_code_sign do
    dart_defines_path = 'dart-defines_dev.json'

    generate

    Dir.chdir('../') do
      sh(
        'flutter build ipa '\
        '--flavor dev '\
        "--dart-define-from-file '#{dart_defines_path}' "\
        '--no-codesign'
      )
    end
  end

  desc 'Build develop app for Simulator'
  lane :build_dev_for_simulator do
    dart_defines_path = 'dart-defines_dev.json'

    generate

    Dir.chdir('../') do
      sh(
        'flutter build ios '\
        '--flavor dev '\
        "--dart-define-from-file '#{dart_defines_path}' "\
        '--debug --simulator'
      )
    end
  end

  desc 'Build production app'
  lane :build_prod do
    generate

    build(
      flavor: 'prod',
      dart_defines_path: 'dart-defines_prod.json',
      export_options_plist_path: './ios/ExportOptions_AppStore.plist'
    )
  end

  desc 'Deploy develop app to Firebase App Distribution'
  lane :deploy_dev do
    build_dev

    firebase_app_distribution(
      app: '1:409733918350:ios:e1fc95560330d3dbfea3df',
      service_credentials_file: 'fastlane/firebase-app-distribution-develop.json',
      groups: 'testers'
    )
  end

  desc 'Deploy production app to App Store Connect'
  lane :deploy_prod do
    build_prod

    deploy_prod_without_build
  end

  desc 'Deploy production app to App Store Connect. '\
    'This lane does not build, so you need to build before running this lane.'
  lane :deploy_prod_without_build do
    Dotenv.load '.env'

    apple_api_key_id = ENV['APPLE_API_KEY_ID'].to_s
    apple_api_issuer_id = ENV['APPLE_API_ISSUER_ID'].to_s

    app_store_connect_api_key_path = 'fastlane/app-store-connect-api-key.p8'

    lane_context[SharedValues::IPA_OUTPUT_PATH] = 'build/ios/ipa/MyPetMelody.ipa'

    api_key = app_store_connect_api_key(
      key_id: apple_api_key_id,
      issuer_id: apple_api_issuer_id,
      key_filepath: app_store_connect_api_key_path
    )

    upload_to_app_store(
      api_key:,
      metadata_path: 'fastlane/ios/metadata',
      screenshots_path: 'fastlane/ios/screenshots',
      skip_metadata: false,
      skip_screenshots: false,
      force: true,
      submit_for_review: true,
      reject_if_possible: true,
      automatic_release: true,
      submission_information: { add_id_info_uses_idfa: false },
      precheck_include_in_app_purchases: false
    )
  end

  private_lane :build do |options|
    flavor = options[:flavor]
    dart_defines_path = options[:dart_defines_path]
    export_options_plist_path = options[:export_options_plist_path]

    Dir.chdir('../') do
      sh(
        'flutter build ipa '\
        "--flavor #{flavor} "\
        "--dart-define-from-file '#{dart_defines_path}' "\
        "--export-options-plist=#{export_options_plist_path}"
      )
    end

    lane_context[SharedValues::IPA_OUTPUT_PATH] = 'build/ios/ipa/MyPetMelody.ipa'
  end
end
