default_platform(:ios)

platform :ios do
  desc 'Build develop app'
  lane :build_dev do
    generate

    Dir.chdir('../') do
      sh('flutter build ipa --dart-define FLAVOR=dev --export-options-plist=ios/ExportOptions_Develop-AdHoc.plist')
    end
  end
end
