inputs:
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - name: Get Python version
      id: get-python-version
      run: |
        python_version="$(cat .python-version)"
        echo "python-version=$python_version" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Cache Python
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.get-python-version.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ steps.get-python-version.outputs.python-version }}
    - name: Cache pip
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
