runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: "temurin"
        java-version: "17"
    # asdf用のバージョン指定ファイルからFlutterのバージョンを読み取り、
    # "-stable" サフィックスを削除したものを環境変数に格納する
    - name: Get Flutter version
      id: get-flutter-version
      run: |
        asdf_flutter_version="$(cat .tool-versions | awk '{print $2}')"
        flutter_version="$(echo $asdf_flutter_version | sed -e 's/-stable//g')"
        echo "flutter-version=$flutter_version" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache Flutter on Linux
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      if: startsWith(runner.os, 'Linux')
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-${{ steps.get-flutter-version.outputs.flutter-version }}
    - name: Cache Flutter on macOS
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      if: startsWith(runner.os, 'macOS')
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-${{ steps.get-flutter-version.outputs.flutter-version }}
    - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2
      with:
        flutter-version: ${{ steps.get-flutter-version.outputs.flutter-version }}
    - name: Enable Swift Package Manager on Flutter
      run: flutter config --enable-swift-package-manager
      shell: bash
    - name: Install FlutterFire CLI
      shell: bash
      # 最新版の v1.1.0 だとdSYMがアップロードできないため、ワークアラウンド
      # https://github.com/invertase/flutterfire_cli/issues/366
      run: dart pub global activate flutterfire_cli 1.0.1
