inputs:
  firebase-options-dart-base64-emulator:
    required: true
  firebase-options-dart-base64-dev:
    required: true
  firebase-options-dart-base64-prod:
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Firebase options files
      shell: bash
      run: |
        echo "${{ inputs.firebase-options-dart-base64-emulator }}" | base64 -d > lib/firebase_options_emulator.dart
        echo "${{ inputs.firebase-options-dart-base64-dev }}" | base64 -d > lib/firebase_options_dev.dart
        echo "${{ inputs.firebase-options-dart-base64-prod }}" | base64 -d > lib/firebase_options_prod.dart

    - name: Generate automatic codes
      shell: bash
      run: bundle exec fastlane generate
