inputs:
  service-account-email:
    required: true
  workload-identity-provider:
    required: true
  tfbackend-file-name:
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
    - name: Cache Terraform Plugins
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: ~/infra/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
      id: "auth"
      with:
        service_account: ${{ inputs.service-account-email }}
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
    - name: Terraform Init
      working-directory: infra
      shell: bash
      run: terraform init -backend-config="${{ inputs.tfbackend-file-name }}"
