inputs:
  service-account-email:
    required: true
  workload-identity-provider:
    required: true
  tfbackend-file-name:
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
    - name: Cache Terraform Plugins
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ~/infra/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d # v2
      id: "auth"
      with:
        service_account: ${{ inputs.service-account-email }}
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
    - name: Terraform Init
      working-directory: infra
      shell: bash
      run: terraform init -backend-config="${{ inputs.tfbackend-file-name }}"
