inputs:
  firebase-options-dart-base64-emulator:
    required: true
  firebase-options-dart-base64-dev:
    required: true
  keystore-jks-base64:
    required: true
  store-password:
    required: true
  key-password:
    required: true
  key-alias:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: ./.github/actions/setup-flutter

    - name: Setup Gradle
      uses: ./.github/actions/setup-gradle

    - name: Generate uncommited files
      uses: ./.github/actions/generate-uncommited-files
      with:
        firebase-options-dart-base64-emulator: ${{ inputs.firebase-options-dart-base64-emulator }}
        firebase-options-dart-base64-dev: ${{ inputs.firebase-options-dart-base64-dev }}

    - name: Generate key store
      uses: ./.github/actions/generate-key-store
      with:
        keystore-jks-base64: ${{ inputs.keystore-jks-base64 }}
        store-password: ${{ inputs.store-password }}
        key-password: ${{ inputs.key-password }}
        key-alias: ${{ inputs.key-alias }}

    - name: Android build
      shell: bash
      run: flutter build appbundle --dart-define FLAVOR=dev
