default_platform(:android)

platform :android do
  desc 'Build develop app'
  lane :build_dev do
    generate

    Dir.chdir('../') do
      sh('flutter build apk --flavor dev --dart-define-from-file dart-defines_dev.json')
    end

    lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] = 'build/app/outputs/flutter-apk/app-dev-release.apk'
  end

  desc 'Build production app'
  lane :build_prod do
    generate

    Dir.chdir('../') do
      sh('flutter build appbundle --flavor prod --dart-define-from-file dart-defines_prod.json')
    end

    lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH] = 'build/app/outputs/bundle/prodRelease/app-prod-release.aab'
  end

  desc 'Deploy develop app to Firebase App Distribution'
  lane :deploy_dev do
    build_dev

    firebase_app_distribution(
      app: '1:409733918350:android:6e0ef3847f6f80a7fea3df',
      service_credentials_file: 'fastlane/firebase-app-distribution-develop.json',
      groups: 'testers'
    )
  end

  desc 'Build production app'
  lane :deploy_prod do
    package_name = 'ide.shota.colomney.MyPetMelody'
    metadata_path = 'fastlane/android/metadata'
    google_play_json_key_path = 'fastlane/google-play-service-account-key.json'

    build_prod

    upload_to_play_store(
      package_name:,
      release_status: 'completed',
      track: 'internal',
      metadata_path:,
      json_key: google_play_json_key_path
    )

    version_code = get_version_code
    upload_to_play_store(
      package_name:,
      version_code:,
      skip_upload_aab: true,
      track: 'internal',
      metadata_path:,
      json_key: google_play_json_key_path,
      track_promote_to: 'production',
      track_promote_release_status: 'completed'
    )
  end
end
